package com.wx.ssm.mapper;

import com.wx.ssm.pojo.Stuff;
import com.wx.ssm.pojo.StuffExample;
import java.util.List;

public interface StuffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuff
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuff
     *
     * @mbg.generated
     */
    int insert(Stuff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuff
     *
     * @mbg.generated
     */
    int insertSelective(Stuff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuff
     *
     * @mbg.generated
     */
    List<Stuff> selectByExample(StuffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuff
     *
     * @mbg.generated
     */
    Stuff selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuff
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Stuff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stuff
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Stuff record);
}