package com.wx.ssm.pojo;

import java.util.Date;

public class Wages {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wages.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wages.Employeeid
     *
     * @mbg.generated
     */
    private Integer employeeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wages.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wages.Time
     *
     * @mbg.generated
     */
    private Integer time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wages.Pay
     *
     * @mbg.generated
     */
    private Integer pay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wages.Month
     *
     * @mbg.generated
     */
    private Date month;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wages.ID
     *
     * @return the value of wages.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wages.ID
     *
     * @param id the value for wages.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wages.Employeeid
     *
     * @return the value of wages.Employeeid
     *
     * @mbg.generated
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wages.Employeeid
     *
     * @param employeeid the value for wages.Employeeid
     *
     * @mbg.generated
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wages.Name
     *
     * @return the value of wages.Name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wages.Name
     *
     * @param name the value for wages.Name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wages.Time
     *
     * @return the value of wages.Time
     *
     * @mbg.generated
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wages.Time
     *
     * @param time the value for wages.Time
     *
     * @mbg.generated
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wages.Pay
     *
     * @return the value of wages.Pay
     *
     * @mbg.generated
     */
    public Integer getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wages.Pay
     *
     * @param pay the value for wages.Pay
     *
     * @mbg.generated
     */
    public void setPay(Integer pay) {
        this.pay = pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wages.Month
     *
     * @return the value of wages.Month
     *
     * @mbg.generated
     */
    public Date getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wages.Month
     *
     * @param month the value for wages.Month
     *
     * @mbg.generated
     */
    public void setMonth(Date month) {
        this.month = month;
    }
}